stages:
  - test
  - build
  - deploy:stg
  - deploy:prd

.deploy-script: &deploy-script
  - sudo -u ${USER} /usr/bin/rsync -rlptogq -P --delete --exclude-from=.rsyncignore . ${ROOT_PATH}/
  - sudo /bin/chown -R ${USER}:${USER} ${ROOT_PATH}/

include:
  - project: 'connector/connector-utils/CI-Templates'
    file: 'code-quality/ci-phpstan.yaml'

code_quality:
  stage: test
  variables:
    STAN_FOLDERS: 'src public/index.php'
    CQ_FOLDERS: 'src public/index.php'
    CQ_PHP_VERSION: '8.2'
    CQ_STANDARDS: '/tmp/code-quality/ConnectorCoreStandard.xml'

build:prod:
  stage: build
  tags:
    - docker
  image: gitlab.jtl-software.com:4567/connector/connector-utils/ci-docker/php/cli:8.2
  script:
    - composer install --no-interaction --no-progress --no-dev --optimize-autoloader --prefer-dist
  artifacts:
    paths:
      - vendor/
    expire_in: 1 hour
    when: always
    name: vendor-prod
  cache:
    key: vendor-prod
    paths:
      - vendor/

build:prod:frontend:
  stage: build
  tags:
    - docker
  image: node:20-alpine
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - public/
    expire_in: 1 hour
    when: always
    name: public-prod
  cache:
    key: node_modules-prod
    paths:
      - frontend/node_modules

build:dev:
  stage: build
  tags:
    - docker
  image: gitlab.jtl-software.com:4567/connector/connector-utils/ci-docker/php/cli:8.2
  script:
    - composer install --no-interaction --no-progress --optimize-autoloader --prefer-dist
  artifacts:
    paths:
      - vendor/
    expire_in: 1 hour
    when: always
    name: vendor-dev
  cache:
    key: vendor-dev
    paths:
      - vendor/

build:dev:frontend:
  stage: build
  tags:
    - docker
  image: node:20-alpine
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - public/
    expire_in: 1 hour
    when: always
    name: public-dev
  cache:
    key: node_modules-dev
    paths:
      - frontend/node_modules

deploy:stg:
  stage: deploy:stg
  allow_failure: false
  script:
    *deploy-script
  tags:
    - ${SERVER}
  dependencies:
    - build:prod
    - build:prod:frontend
  variables:
    USER: 'php-tester'
    ROOT_PATH: '/var/www/tester-stg.jtl-connector.de/source'
  environment:
    name: staging/${SERVER}
    url: 'https://tester-stg.jtl-connector.de'
  when: manual
  parallel:
    matrix:
      - SERVER:
          - 'div04-stg-ddu01'
deploy:prd:
  stage: deploy:prd
  allow_failure: false
  script:
    *deploy-script
  tags:
    - ${SERVER}
  dependencies:
    - build:prod
    - build:prod:frontend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG
  variables:
    USER: 'php-tester'
    ROOT_PATH: '/var/www/tester.jtl-connector.de/source'
  environment:
    name: production/${SERVER}
    url: 'https://tester.jtl-connector.de'
  when: manual
  parallel:
    matrix:
      - SERVER:
          - 'div04-prd-ddu01'