stages:
  - test
  - build
  - deploy

include:
  - project: 'connector/connector-utils/CI-Templates'
    file: 'code-quality/ci-phpstan.yaml'

code_quality:
  stage: test
  variables:
    STAN_FOLDERS: 'src public/index.php'
    CQ_FOLDERS: 'src public/index.php'
    CQ_PHP_VERSION: '8.2'
    CQ_STANDARDS: '/tmp/code-quality/ConnectorCoreStandard.xml'

build:prod:
  stage: build
  tags:
    - docker
  image: gitlab.jtl-software.com:4567/connector/connector-utils/ci-docker/php/cli:8.2
  script:
    - composer install --no-interaction --no-progress --no-dev --optimize-autoloader --prefer-dist
  artifacts:
    paths:
      - vendor/
    expire_in: 1 hour
    when: always
    name: vendor-prod
  cache:
    key: vendor-prod
    paths:
      - vendor/

build:prod:frontend:
  stage: build
  tags:
    - docker
  image: node:20-alpine
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - public/
    expire_in: 1 hour
    when: always
    name: public-prod
  cache:
    key: node_modules-prod
    paths:
      - frontend/node_modules

build:dev:
  stage: build
  tags:
    - docker
  image: gitlab.jtl-software.com:4567/connector/connector-utils/ci-docker/php/cli:8.2
  script:
    - composer install --no-interaction --no-progress --optimize-autoloader --prefer-dist
  artifacts:
    paths:
      - vendor/
    expire_in: 1 hour
    when: always
    name: vendor-dev
  cache:
    key: vendor-dev
    paths:
      - vendor/

build:dev:frontend:
  stage: build
  tags:
    - docker
  image: node:20-alpine
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - public/
    expire_in: 1 hour
    when: always
    name: public-dev
  cache:
    key: node_modules-dev
    paths:
      - frontend/node_modules